# Generated by Django 5.0 on 2023-12-11 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0002_stuff_alter_workassignment_assigned_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='id',
        ),
        migrations.AlterField(
            model_name='request',
            name='number',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
