# Generated by Django 4.2.8 on 2023-12-11 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tech', '0003_remove_request_id_alter_request_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ispolnitel', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='request',
            name='client',
            field=models.ForeignKey(limit_choices_to={'ispolnitel': False}, on_delete=django.db.models.deletion.CASCADE, to='tech.userprofile'),
        ),
        migrations.AlterField(
            model_name='workassignment',
            name='assigned_to',
            field=models.ForeignKey(limit_choices_to={'ispolnitel': True}, on_delete=django.db.models.deletion.CASCADE, to='tech.userprofile'),
        ),
    ]
