# Generated by Django 4.2.8 on 2023-12-16 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0005_delete_client_delete_stuff'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='date_closed',
            field=models.DateField(blank=True, null=True),
        ),
    ]
