# Generated by Django 4.2.8 on 2023-12-16 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0006_request_date_closed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workassignment',
            name='comments',
        ),
    ]
