# Generated by Django 4.2.8 on 2023-12-16 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0008_remove_userprofile_ispolnitel_userprofile_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='client',
            field=models.ForeignKey(limit_choices_to={'role': 'user', 'user__is_staff': False}, on_delete=django.db.models.deletion.CASCADE, to='tech.userprofile'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(limit_choices_to={'role': 'ispolnitel'}, on_delete=django.db.models.deletion.CASCADE, to='tech.userprofile')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tech.request')),
            ],
        ),
    ]
