# Generated by Django 4.2.8 on 2023-12-16 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0009_alter_request_client_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tech.request'),
        ),
    ]
