# Generated by Django 4.2.8 on 2023-12-19 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0011_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='is_read',
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('pending', 'В ожидании'), ('in_progress', 'В работе'), ('completed', 'Выполнена')], default='pending', max_length=20),
        ),
    ]
